### ISSUE TITLE
Add poolboy for connection/channel pooling.

### ISSUE THREAD

**Issue by nyo16** [cjab/weddell#5]
I like the implementation of https://github.com/bzzt/bigtable for connection pooling.
Do you think we can do it with the current structure?

**Comment by cjab** [comment]
Hi there @nyo16, apologies for the slow reply. I do think this is possible but it will take a little bit of restructuring. For my uses I haven't run into problems with a single connection but I admit I haven't needed anything with incredibly high throughput. Just curious if you've run into problems.
